---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapi
  labels:
    app: usersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usersapi
  template:
    metadata:
      labels:
        app: usersapi
    spec:
      containers:
        - name: usersapi
          image: ghcr.io/yokawasa/users-api-flask-mysql/users-api:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: usersapi-secrets
                  key: db_root_password
            - name: db_name
              value: usersapi

---
apiVersion: v1
kind: Service
metadata:
  name: usersapi
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: usersapi
  type: LoadBalancer
