#FROM mysql:5.7
## ARM-based Architectures
# https://zenn.dev/ohkisuguru/scraps/5b9d76333ff13d
FROM mysql@sha256:92ad1d7e3f8eb7e67d35bf251912fb7cd12676a601dc90b6beb1aece7c1f5073
ADD schema.sql /docker-entrypoint-initdb.d
